# 全局推送配置数据
push-data:
  # 1 钉钉机器人
  DingDing:
    Secret: ""
    Token: ""
  # 2 PushPlus
  PushPlus:
    Token: ""
  # 3 Server酱
  Server_Turbo:
    Token: ""
  # 4 邮件、用户侧必须配置接收地址
  Email:
    email_username: "@"
    email_password: ""
    email_address: ""
    email_port: ""

# 程序运行时间（满足此时间才推送信息，否则本地输出），早上7点运行时推送，其余时间运行不推送填07，留空为无论何时都推送
time: " "

# 每位用户随机时间（秒）
range_time: "0-1"

# 腾讯地图api密钥，获取地址经纬度需要
api_token: "UGMBZ-CINWR-DDRW5-W52AK-D3ENK-ZEBRC"

# 是否开启实习报告（打卡成功才会提交）
# 使用GPT官方库，可使用支持官方库的api地址和key
gpt_data:
  # 指定GPT-API接口，留空使用官方url（需梯子），你可填写国内镜像站，例如chatanywhere：https://api.chatanywhere.com.cn/v1
  url: https://api.xeduapi.com/v1
  # key，会用你就知道填什么，请确保有足够的余额
  key: 
# 是否开启日报，每日提交
day_report: True
# 是否开启周报，每周六提交
week_report: True
# 是否开启月报，每月月底最后一天提交
month_report: False


# 是否开启节假日判断（如果当天为中国法定节假日，则跳过打卡）
holiday_pass: False

# 日志，仅支持smtp邮件推送，推送的为简化版日志，详细日志见log内具体文件'''
log_report: False
log_report_data:
    # smtp用户名
    "emailUsername": ""
    # smtp密码
    "emailPassword": ""
    # smtp服务器地址
    "emailAddress": ""
    # smtp端口
    "emailPort": ""
    # 接收日志邮箱
    "Receiver": ""
